name: backend-checks
on:
  push:
    branches:
      - main
    paths:
    - 'backend/**'
  pull_request:
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  checks:
    name: backend-checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
      - name: Install
        run: go get .
      - name: Build
        run: go build .
      - name: Tests
        run: go test
