name: create and publish Docker images

on:
  push:
    paths:
    - 'frontend/**'
    - 'backend/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/pluralkit
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    if: github.repository == 'PluralKit/statuspage'
    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta_frontend
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_frontend
          tags: |
            type=ref,event=branch
            type=sha,format=long
            
      - uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          target: caddy
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}

      - id: meta_backend
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_backend
          tags: |
            type=ref,event=branch
            type=sha,format=long
            
      - uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          target: backend
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}