name: Build and push Docker images
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 'docker build'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: github.repository == 'PluralKit/statuspage'
    steps:
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          target: backend
          tags: ghcr.io/PluralKit/statuspage_backend:latest
          push: true
      - uses: docker/build-push-action@v2
        with:
          context: .
          target: frontend
          tags: ghcr.io/PluralKit/statuspage_frontend:latest
          push: true
